import type { SpeedTier } from '@/lib/speed-tier';
import type { ProbePresetTarget } from './components/probe-preset-schema';
export interface SystemSettings {
  siteName: string;
  siteDescription: string;
  publicBaseUrl: string;
  logoUrl: string;
  faviconUrl: string;
  siteAnnouncement: string;
  siteAnnouncementsJson: string;
  footerCopyright: string;
  supportTelegramUrl: string;
  supportDiscordUrl: string;
  supportEmail: string;
  supportCustomUrl: string;
  registrationEnabled: boolean;
  systemTimezone: string;
  defaultPlanId: string | null;
  defaultBalance: number;
  emailDomainMode: 'none' | 'whitelist' | 'blacklist';
  emailDomainList: string[];
  passwordMinLength: number;
  passwordRequireLowercase: boolean;
  passwordRequireUppercase: boolean;
  passwordRequireDigit: boolean;
  passwordRequireSpecial: boolean;
  subscriptionBaseUrl: string;
  subscriptionShortLinksEnabled: boolean;
  subscriptionEffectsSyncEnabled: boolean;
  subscriptionUpdateIntervalHours: number;
  appendSubscriptionSpeedBadge: boolean;
  speedLimitUnitConversionEnabled: boolean;
  speedLimitColorTiers: SpeedTier[];
  defaultTemplateId: string | null;
  publicLinesEnabled: boolean;
  includeUsageHeaders: boolean;
  deviceLimitEnabled: boolean;
  deviceOnlineWindowSecs: number;
  heartbeatTimeoutSecs: number;
  configSyncDebounceMs: number;
  defaultPollIntervalSecs: number;
  binaryDownloadBaseUrl: string;
  githubRepoUrl: string;
  githubMirrorUrls: string[];
  probePresetTargets: ProbePresetTarget[];
  jwtSessionDays: number;
  customCss: string;
  customHeadHtml: string;
  lineSpeedtestEnabled: boolean;
  lineSpeedtestIntervalMins: number;
  lineSpeedtestTargetUrl: string;
  lineSpeedtestTimeoutMs: number;
  probeSingboxFallbackEnabled: boolean;
  certificateExpiryWarningDays: number;
  certificateMailEnabled: boolean;
  certificateMailRecipients: string[];
  smtpEnabled: boolean;
  smtpHost: string;
  smtpPort: number;
  smtpSecure: boolean;
  smtpUser: string;
  smtpPass: string;
  smtpFrom: string;
  emailVerificationEnabled: boolean;
  enforceEmailVerification: boolean;
  captchaMode: 'OFF' | 'LOCAL' | 'TURNSTILE';
  turnstileSiteKey: string;
  turnstileSecretKey: string;
  logsRetentionDays: number;
  logsMaxCount: number;
  logsMinIngestLevel: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';
  trafficHourlyRetentionDays: number;
  nodeRateRetentionDays: number;
  agentLogMaxSizeMb: number;
  agentLogMaxFiles: number;
  landingEnabled: boolean;
  landingHeroBadge: string;
  landingHeroTitle: string;
  landingHeroSubtitle: string;
  landingShowFeatures: boolean;
  landingShowPlans: boolean;
  landingShowFaq: boolean;
  landingCustomFeaturesJson: string;
  landingCustomFaqJson: string;
}
