import type { SystemSettings } from './settings-types';
import type { SettingsForm } from './settings-schema';
import { DEFAULT_SPEED_TIERS } from '@/lib/speed-tier';
import { derivePrimaryBannerText, parseAnnouncements } from '@/lib/announcements';
import { toProbePresetFormValue, toProbePresetTarget } from './components/probe-preset-schema';
function cleanStr(value: string | null | undefined, fallback = ''): string {
  if (value == null || value === 'undefined') return fallback;
  return value;
}

export function toForm(settings: SystemSettings, availablePublicPlanIds?: Set<string>): SettingsForm {
  const rawPlanId = cleanStr(settings.defaultPlanId, '');
  const resolvedPlanId =
    !rawPlanId || (availablePublicPlanIds && !availablePublicPlanIds.has(rawPlanId))
      ? 'none'
      : rawPlanId;

  return {
    siteName: cleanStr(settings.siteName),
    siteDescription: cleanStr(settings.siteDescription),
    publicBaseUrl: cleanStr(settings.publicBaseUrl),
    logoUrl: cleanStr(settings.logoUrl),
    faviconUrl: cleanStr(settings.faviconUrl),
    siteAnnouncement: cleanStr(settings.siteAnnouncement),
    siteAnnouncementsJson: cleanStr(settings.siteAnnouncementsJson, '[]') || '[]',
    footerCopyright: cleanStr(settings.footerCopyright),
    supportTelegramUrl: cleanStr(settings.supportTelegramUrl),
    supportDiscordUrl: cleanStr(settings.supportDiscordUrl),
    supportEmail: cleanStr(settings.supportEmail),
    supportCustomUrl: cleanStr(settings.supportCustomUrl),
    registrationEnabled: settings.registrationEnabled,
    systemTimezone: cleanStr(settings.systemTimezone, 'Asia/Shanghai') || 'Asia/Shanghai',
    defaultPlanId: resolvedPlanId,
    defaultBalanceYuan: settings.defaultBalance / 100,
    emailDomainMode: settings.emailDomainMode,
    emailDomainListText: settings.emailDomainList.join('\n'),
    passwordMinLength: settings.passwordMinLength,
    passwordRequireLowercase: settings.passwordRequireLowercase ?? true,
    passwordRequireUppercase: settings.passwordRequireUppercase ?? false,
    passwordRequireDigit: settings.passwordRequireDigit ?? true,
    passwordRequireSpecial: settings.passwordRequireSpecial ?? false,
    subscriptionBaseUrl: cleanStr(settings.subscriptionBaseUrl),
    subscriptionShortLinksEnabled: settings.subscriptionShortLinksEnabled,
    subscriptionEffectsSyncEnabled: settings.subscriptionEffectsSyncEnabled ?? true,
    subscriptionUpdateIntervalHours: settings.subscriptionUpdateIntervalHours,
    appendSubscriptionSpeedBadge: settings.appendSubscriptionSpeedBadge ?? true,
    speedLimitUnitConversionEnabled: settings.speedLimitUnitConversionEnabled ?? true,
    speedLimitColorTiers: settings.speedLimitColorTiers?.length ? settings.speedLimitColorTiers : DEFAULT_SPEED_TIERS,
    defaultTemplateId: cleanStr(settings.defaultTemplateId, 'none') || 'none',
    publicLinesEnabled: settings.publicLinesEnabled,
    includeUsageHeaders: settings.includeUsageHeaders,
    deviceLimitEnabled: settings.deviceLimitEnabled ?? true,
    deviceOnlineWindowSecs: settings.deviceOnlineWindowSecs ?? 60,
    heartbeatTimeoutSecs: settings.heartbeatTimeoutSecs,
    configSyncDebounceMs: settings.configSyncDebounceMs,
    defaultPollIntervalSecs: settings.defaultPollIntervalSecs,
    binaryDownloadBaseUrl: cleanStr(settings.binaryDownloadBaseUrl),
    githubRepoUrl: cleanStr(settings.githubRepoUrl),
    githubMirrorUrlsText: settings.githubMirrorUrls.filter((item) => item !== 'undefined').join('\n'),
    probePresetTargets: settings.probePresetTargets.map(toProbePresetFormValue),
    jwtSessionDays: settings.jwtSessionDays,
    customCss: cleanStr(settings.customCss),
    customHeadHtml: cleanStr(settings.customHeadHtml),
    lineSpeedtestEnabled: settings.lineSpeedtestEnabled,
    lineSpeedtestIntervalMins: settings.lineSpeedtestIntervalMins,
    lineSpeedtestTargetUrl: cleanStr(settings.lineSpeedtestTargetUrl, 'https://cp.cloudflare.com/generate_204'),
    lineSpeedtestTimeoutMs: settings.lineSpeedtestTimeoutMs ?? 10000,
    probeSingboxFallbackEnabled: settings.probeSingboxFallbackEnabled ?? true,
    smtpEnabled: settings.smtpEnabled,
    smtpHost: cleanStr(settings.smtpHost),
    smtpPort: settings.smtpPort,
    smtpSecure: settings.smtpSecure,
    smtpUser: cleanStr(settings.smtpUser),
    smtpPass: cleanStr(settings.smtpPass),
    smtpFrom: cleanStr(settings.smtpFrom),
    emailVerificationEnabled: settings.emailVerificationEnabled,
    enforceEmailVerification: settings.enforceEmailVerification ?? false,
    captchaMode: settings.captchaMode,
    turnstileSiteKey: cleanStr(settings.turnstileSiteKey),
    turnstileSecretKey: cleanStr(settings.turnstileSecretKey),
    logsRetentionDays: settings.logsRetentionDays,
    logsMaxCount: settings.logsMaxCount,
    logsMinIngestLevel: settings.logsMinIngestLevel,
    trafficHourlyRetentionDays: settings.trafficHourlyRetentionDays,
    nodeRateRetentionDays: settings.nodeRateRetentionDays,
    agentLogMaxSizeMb: settings.agentLogMaxSizeMb,
    agentLogMaxFiles: settings.agentLogMaxFiles,
    landingEnabled: settings.landingEnabled ?? true,
    landingHeroBadge: cleanStr(settings.landingHeroBadge),
    landingHeroTitle: cleanStr(settings.landingHeroTitle),
    landingHeroSubtitle: cleanStr(settings.landingHeroSubtitle),
    landingShowFeatures: settings.landingShowFeatures ?? true,
    landingShowPlans: settings.landingShowPlans ?? true,
    landingShowFaq: settings.landingShowFaq ?? true,
    landingCustomFeaturesJson: cleanStr(settings.landingCustomFeaturesJson, '[]') || '[]',
    landingCustomFaqJson: cleanStr(settings.landingCustomFaqJson, '[]') || '[]'
  };
}

export function toPayload(values: SettingsForm) {
  const parsedAnnouncements = parseAnnouncements(values.siteAnnouncementsJson, values.siteAnnouncement);
  const derivedBanner = derivePrimaryBannerText(parsedAnnouncements);

  return {
    siteName: values.siteName,
    siteDescription: values.siteDescription,
    publicBaseUrl: values.publicBaseUrl.trim(),
    logoUrl: values.logoUrl.trim(),
    faviconUrl: values.faviconUrl.trim(),
    siteAnnouncement: derivedBanner,
    siteAnnouncementsJson: values.siteAnnouncementsJson,
    footerCopyright: values.footerCopyright,
    supportTelegramUrl: values.supportTelegramUrl.trim(),
    supportDiscordUrl: values.supportDiscordUrl.trim(),
    supportEmail: values.supportEmail.trim(),
    supportCustomUrl: values.supportCustomUrl.trim(),
    registrationEnabled: values.registrationEnabled,
    systemTimezone: values.systemTimezone,
    defaultPlanId: values.defaultPlanId === 'none' ? null : values.defaultPlanId,
    defaultBalance: Math.round(values.defaultBalanceYuan * 100),
    emailDomainList: values.emailDomainListText.split(/\r?\n|,/).map((item) => item.trim().toLowerCase().replace(/^@+/, '')).filter(Boolean),
    emailDomainMode: values.emailDomainMode,
    passwordMinLength: values.passwordMinLength,
    passwordRequireLowercase: values.passwordRequireLowercase,
    passwordRequireUppercase: values.passwordRequireUppercase,
    passwordRequireDigit: values.passwordRequireDigit,
    passwordRequireSpecial: values.passwordRequireSpecial,
    subscriptionBaseUrl: values.subscriptionBaseUrl.trim(),
    subscriptionShortLinksEnabled: values.subscriptionShortLinksEnabled,
    subscriptionEffectsSyncEnabled: values.subscriptionEffectsSyncEnabled,
    subscriptionUpdateIntervalHours: values.subscriptionUpdateIntervalHours,
    appendSubscriptionSpeedBadge: values.appendSubscriptionSpeedBadge,
    speedLimitUnitConversionEnabled: values.speedLimitUnitConversionEnabled,
    speedLimitColorTiers: values.speedLimitColorTiers,
    publicLinesEnabled: values.publicLinesEnabled,
    includeUsageHeaders: values.includeUsageHeaders,
    deviceLimitEnabled: values.deviceLimitEnabled,
    deviceOnlineWindowSecs: values.deviceOnlineWindowSecs,
    heartbeatTimeoutSecs: values.heartbeatTimeoutSecs,
    configSyncDebounceMs: values.configSyncDebounceMs,
    defaultPollIntervalSecs: values.defaultPollIntervalSecs,
    binaryDownloadBaseUrl: values.binaryDownloadBaseUrl.trim(),
    githubRepoUrl: values.githubRepoUrl.trim(),
    githubMirrorUrls: values.githubMirrorUrlsText.split(/\r?\n/).map((item) => item.trim()).filter(Boolean),
    probePresetTargets: values.probePresetTargets.map(toProbePresetTarget),
    jwtSessionDays: values.jwtSessionDays,
    customCss: values.customCss,
    customHeadHtml: values.customHeadHtml,
    lineSpeedtestEnabled: values.lineSpeedtestEnabled,
    lineSpeedtestIntervalMins: values.lineSpeedtestIntervalMins,
    lineSpeedtestTargetUrl: values.lineSpeedtestTargetUrl.trim(),
    lineSpeedtestTimeoutMs: values.lineSpeedtestTimeoutMs,
    // 隐藏的兼容配置不提交，保存其他设置时保留服务端历史值。
    smtpEnabled: values.smtpEnabled,
    smtpHost: values.smtpHost,
    smtpPort: values.smtpPort,
    smtpSecure: values.smtpSecure,
    smtpUser: values.smtpUser,
    smtpPass: values.smtpPass,
    smtpFrom: values.smtpFrom,
    emailVerificationEnabled: values.emailVerificationEnabled,
    enforceEmailVerification: values.enforceEmailVerification,
    captchaMode: values.captchaMode,
    turnstileSiteKey: values.turnstileSiteKey,
    turnstileSecretKey: values.turnstileSecretKey,
    logsRetentionDays: values.logsRetentionDays,
    logsMaxCount: values.logsMaxCount,
    logsMinIngestLevel: values.logsMinIngestLevel,
    trafficHourlyRetentionDays: values.trafficHourlyRetentionDays,
    nodeRateRetentionDays: values.nodeRateRetentionDays,
    agentLogMaxSizeMb: values.agentLogMaxSizeMb,
    agentLogMaxFiles: values.agentLogMaxFiles,
    landingEnabled: values.landingEnabled,
    landingHeroBadge: values.landingHeroBadge,
    landingHeroTitle: values.landingHeroTitle,
    landingHeroSubtitle: values.landingHeroSubtitle,
    landingShowFeatures: values.landingShowFeatures,
    landingShowPlans: values.landingShowPlans,
    landingShowFaq: values.landingShowFaq,
    landingCustomFeaturesJson: values.landingCustomFeaturesJson,
    landingCustomFaqJson: values.landingCustomFaqJson
  };
}
export function defaultSettingsForm(): SettingsForm {
  return toForm({
      siteName: '', siteDescription: '', publicBaseUrl: '', logoUrl: '', faviconUrl: '', siteAnnouncement: '', siteAnnouncementsJson: '[]', footerCopyright: '',
      supportTelegramUrl: '', supportDiscordUrl: '', supportEmail: '', supportCustomUrl: '', registrationEnabled: false,
      systemTimezone: 'Asia/Shanghai',
      defaultPlanId: null, defaultBalance: 0, emailDomainMode: 'none',
      emailDomainList: [], passwordMinLength: 8, passwordRequireLowercase: true, passwordRequireUppercase: false, passwordRequireDigit: true, passwordRequireSpecial: false, subscriptionBaseUrl: '', subscriptionShortLinksEnabled: false, subscriptionEffectsSyncEnabled: true, subscriptionUpdateIntervalHours: 24, appendSubscriptionSpeedBadge: true,
      speedLimitUnitConversionEnabled: true, speedLimitColorTiers: DEFAULT_SPEED_TIERS,
      defaultTemplateId: null, publicLinesEnabled: true, includeUsageHeaders: true, deviceLimitEnabled: true, deviceOnlineWindowSecs: 60, heartbeatTimeoutSecs: 15,
      configSyncDebounceMs: 250, defaultPollIntervalSecs: 15, binaryDownloadBaseUrl: '', githubRepoUrl: __DEFAULT_GITHUB_REPO_URL__, githubMirrorUrls: [], probePresetTargets: [],
      jwtSessionDays: 1, customCss: '', customHeadHtml: '',
      lineSpeedtestEnabled: true, lineSpeedtestIntervalMins: 30,
      lineSpeedtestTargetUrl: 'https://cp.cloudflare.com/generate_204', lineSpeedtestTimeoutMs: 10000,
      probeSingboxFallbackEnabled: true,
      smtpEnabled: false, smtpHost: '', smtpPort: 587, smtpSecure: false, smtpUser: '', smtpPass: '', smtpFrom: '',
      emailVerificationEnabled: false, enforceEmailVerification: false, captchaMode: 'OFF', turnstileSiteKey: '', turnstileSecretKey: '',
      logsRetentionDays: 7, logsMaxCount: 100000, logsMinIngestLevel: 'INFO', trafficHourlyRetentionDays: 90,
      nodeRateRetentionDays: 30, agentLogMaxSizeMb: 50, agentLogMaxFiles: 5,
      landingEnabled: true, landingHeroBadge: '', landingHeroTitle: '', landingHeroSubtitle: '',
      landingShowFeatures: true, landingShowPlans: true, landingShowFaq: true,
      landingCustomFeaturesJson: '[]', landingCustomFaqJson: '[]'
  });
}
